const GOOGLE_CAPTCHA_SITE_KEY = import.meta.env.VITE_GOOGLE_CAPTCHA_SITE_KEY;
const GOOGLE_CAPTCHA_SECRET_KEY = import.meta.env.VITE_GOOGLE_CAPTCHA_SECRET_KEY;

export { GOOGLE_CAPTCHA_SITE_KEY, GOOGLE_CAPTCHA_SECRET_KEY };
